// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InstructionController from "./instruction_controller"
application.register("instruction", InstructionController)

import TabController from "./tab_controller"
application.register("tab", TabController)

import TagController from "./tag_controller"
application.register("tag", TagController)

import TitleCountController from "./title_count_controller"
application.register("title-count", TitleCountController)
