// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AnalyticsController from "./analytics_controller"
application.register("analytics", AnalyticsController)

import CommentReplyModalController from "./comment_reply_modal_controller"
application.register("comment-reply-modal", CommentReplyModalController)

import EditCommentModalController from "./edit_comment_modal_controller"
application.register("edit-comment-modal", EditCommentModalController)

import EditReplyModalController from "./edit_reply_modal_controller"
application.register("edit-reply-modal", EditReplyModalController)

import EditShortcutController from "./edit_shortcut_controller"
application.register("edit-shortcut", EditShortcutController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InstructionController from "./instruction_controller"
application.register("instruction", InstructionController)

import ShortcutIndexController from "./shortcut_index_controller"
application.register("shortcut-index", ShortcutIndexController)

import TabController from "./tab_controller"
application.register("tab", TabController)

import TagController from "./tag_controller"
application.register("tag", TagController)

import TitleCountController from "./title_count_controller"
application.register("title-count", TitleCountController)
