inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rubycw

AllCops:
  # 最新のルールを適用する
  NewCops: enable
  # デフォルトで全部disableにする
  DisabledByDefault: true
  # 何のルールに引っかかったか表示する
  DisplayCopNames: true
  # rubocop-capybaraなどを推奨しない
  SuggestExtensions: false
  # rubocop対象外(リポジトリ毎で調節)
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/*"
    - "config/puma.rb"
    - "config/initializers/**/*"
    - "config/locales/**/*"

# Rails固有のルール
Rails/Output:
  Enabled: true

# 文字列による配列の%記法のチェック
Style/WordArray:
  Enabled: true
  MinSize: 3

# シンボルの%記法のチェック
Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

# # シングルクォーテーションを推奨する
# Style/StringLiterals:
#   Enabled: true
#   EnforcedStyle: single_quotes

# ハッシュのシンボルがどうとかの話
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19 # ハッシュ記法の統一

# ハッシュリテラル内のスペース
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: space # { key: value } など

# メソッド呼び出し時のスペース
Layout/SpaceBeforeFirstArg:
  Enabled: true

# メソッドの改行ルール
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Rails/Validation:
  Enabled: true

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Rubycw:
  Enabled: true

Security:
  Enabled: true
