- id: 1
  thumbnail: "thumbnail1"
  title: "一瞬で電話番号を検索"
  description: "知らない番号から電話がかかってきた時に、一瞬で検索できるショートカットです。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/28a0998aa38e4c6587eed978c9dbdde8"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "設定アプリを開いて、アクセシビリティ > タッチ > 背面タップ > ダブルタップ"
    - step3: "下にスクロールして、ショートカットの小さい文字のところにある「電話番号検索」を選択すると完了です！"
- id: 2
  thumbnail: "thumbnail2"
  title: "充電完了までの残り時間を表示"
  description: "充電器に接続した時に、充電完了までの残り時間を表示してくれるショートかっとです。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/af6a1a32acfa48c18fa796dae684a060"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "ショートカットアプリを開いて、オートメーションのタブを選択"
    - step3: "右上のプラスまたは新規オートメーションを作成をタップ"
    - step4: "充電器を選択して、すぐに実行を選択し、右上の次へをタップ"
    - step5: "検索欄から充電と検索して、充電完了タップすると設定完了です！"
- id: 3
  thumbnail: "thumbnail3"
  title: "ロック画面から一瞬で録音"
  description: "ロック画面からワンタップで録音ができるショートカットです。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/64e2efb4367c4a0ea04faad7727469b1"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "画面の上を下にスワイプして画面を長押し"
    - step3: "カスタマイズをタップして、左側のロック画面を選択"
    - step4: "ウィジェットを追加をタップして、ショートカットを選択しアイコンをタップ"
    - step5: "もう一度アイコンをタップして、一瞬で録音を選択したら設定完了です"
