- id: 1
  thumbnail: "thumbnail1"
  title: "一瞬で電話番号を検索"
  description: "知らない番号から電話がかかってきた時に、一瞬で検索できるショートカットです。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/28a0998aa38e4c6587eed978c9dbdde8"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "設定アプリを開いて、アクセシビリティ > タッチ > 背面タップ > ダブルタップ"
    - step3: "下にスクロールして、ショートカットの小さい文字のところにある「電話番号検索」を選択すると完了です！"
- id: 2
  thumbnail: "thumbnail2"
  title: "充電完了までの残り時間を表示"
  description: "充電器に接続した時に、充電完了までの残り時間を表示してくれるショートかっとです。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/af6a1a32acfa48c18fa796dae684a060"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "ショートカットアプリを開いて、オートメーションのタブを選択"
    - step3: "右上のプラスまたは新規オートメーションを作成をタップ"
    - step4: "充電器を選択して、すぐに実行を選択し、右上の次へをタップ"
    - step5: "検索欄から充電と検索して、充電完了タップすると設定完了です！"
- id: 3
  thumbnail: "thumbnail3"
  title: "ロック画面から一瞬で録音"
  description: "ロック画面からワンタップで録音ができるショートカットです。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/64e2efb4367c4a0ea04faad7727469b1"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "画面の上を下にスワイプして画面を長押し"
    - step3: "カスタマイズをタップして、左側のロック画面を選択"
    - step4: "ウィジェットを追加をタップして、ショートカットを選択しアイコンをタップ"
    - step5: "もう一度アイコンをタップして、一瞬で録音を選択したら設定完了です"
- id: 4
  thumbnail: "thumbnail4"
  title: "写真アプリだけで写真合成"
  description: "純正の写真アプリだけで写真の被写体を別の写真に合成することができます"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/4b2dcfb98d5b4178851a98f177b8d42e"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "写真アプリを開いて合成した被写体が写った写真を選択"
    - step3: "左下の共有マークをタップして、魔法の合成（このショートカット）をタップ"
    - step4: "背景画像にしたい写真を選択して、位置とサイズを調整"
    - step5: "右下の完了ボタンをタップしたら合成完了です！"
- id: 5
  thumbnail: "thumbnail5"
  title: "らくらく決済"
  description: "ワンタップでPayPayや楽天ペイなどの決済アプリ一覧を表示して一瞬で開くことができます。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/f4aff2ce62bc4d809a75296f17ff03ba"
  instructions:
    - step1: "上記リンクからショートカットをダウンロード"
    - step2: "画面の上の部分を下にスワイプして、画面を長押し"
    - step3: "下のカスタマイズをタップして、左のロック画面を選択"
    - step4: "下にあるカメラかライトの左上のマイナスボタンをタップして、プラスマークをタップ"
    - step5: "ショートカットのショートカットを選択"
    - step6: "選択をタップして、マイショートカットから、らくらく決済（このショートカット）を選択"
    - step7: "右上の完了を押すとこれで設定完了です"
- id: 6
  thumbnail: "thumbnail6"
  title: "ワンタップでWi-Fi完全オフ"
  description: "コントロールセンターからワンタップでWi-Fiを完全にオフにすることができます。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/b80ac478354b4ce9a6f090dc354543a8"
  instructions:
    - step1: "上記のリンクからショートカットをダウンロード"
    - step2: "右上を下にシュッとスワイプしてコントロールセンターを表示"
    - step3: "余白を長押しして、一番下のコントロールを追加をタップ"
    - step4: "ショートカットの中からショートカットを選択"
    - step5: "選択をタップして、マイショートカットから、Wi-Fiオフ（このショートカット）を選択したら設定完了です"
- id: 7
  thumbnail: "thumbnail7"
  title: "ロック画面から一瞬でGoogle map検索"
  description: "ロック画面からこのショートカットを起動すると、コンビニや駐車場、ガソスタなどの選択肢が出てきて、それを選択すると一瞬で検索することができるショートカットです。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/8e2c0a63089d49e7879f8e5e89b968b7"
  instructions:
    - step1: "上記のリンクからショートカットをダウンロード"
    - step2: "画面の上の部分を下にスワイプして、画面を長押し"
    - step3: "下のカスタマイズをタップして、左のロック画面を選択"
    - step4: "下にあるカメラかライトの左上のマイナスボタンをタップして、プラスマークをタップ"
    - step5: "ショートカットのショートカットを選択"
    - step6: "選択をタップして、マイショートカットから、秒でGmap（このショートカット）を選択"
    - step7: "右上の完了を押すとこれで設定完了です"
- id: 8
  thumbnail: "thumbnail8"
  title: "スピーカーから水を排出"
  description: "iPhoneが水没した時にスピーカーから水を出すためのショートカット"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/cb421cc53c174311990695a7eacd4fb8"
  instructions:
    - step1: "上記のリンクからショートカットをダウンロード"
    - step2: "水没させてしまった時に、ショートカットアプリから水を排出（このショートカット）をタップすると音声が流れてスピーカーから水を排出することができます。"
- id: 9
  thumbnail: "thumbnail9"
  title: "コントロールセンターを片手でも開きやすく"
  description: "画面の右上をスワイプしないと開けないコントロールセンターですが、このショートカットを使えば、画面の右下からワンタップで開くことができるようになります。"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/55992c04e2cd4737846cc7042ff2c6ef"
  instructions:
    - step1: "上記のリンクからショートカットをダウンロード"
    - step2: "ショートカットアプリからコントロール（このショートカット）の右上の点々をタップ"
    - step3: "下の共有マークをタップして、ホーム画面に追加を選択"
    - step4: "画面の右下の方に配置したら設定完了です"
- id: 10
  thumbnail: "thumbnail10"
  title: "充電節約モード"
  description: "充電の残量が残り少ない時などに、できるだけ節約するためのモードに変更することができます"
  youtube_url: ""
  download_url: "https://www.icloud.com/shortcuts/107c176cb84349cb9ff29430b850d6a8"
  instructions:
    - step1: "上記のリンクからショートカットをダウンロード"
    - step2: "ショートカットアプリから充電節約（このショートカット）をタップすると完了です"
